# Version: 0.0.1
FROM ubuntu
MAINTAINER stefaman "stefaman@qq.com"
ENV REFRESHED_AT 2017-06-12
RUN apt-get update
RUN apt-get install -y nginx
#RUN echo "I'im in container" >/usr/share/nginx/html/index.html
EXPOSE 80
